// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package marketclient

import (
	"context"

	"greet/market/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNativeTokenPriceRequest  = market.GetNativeTokenPriceRequest
	GetNativeTokenPriceResponse = market.GetNativeTokenPriceResponse
	GetPairInfoByTokenRequest   = market.GetPairInfoByTokenRequest
	GetPairInfoByTokenResponse  = market.GetPairInfoByTokenResponse
	Request                     = market.Request
	Response                    = market.Response

	Market interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error)
		GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error)
	}

	defaultMarket struct {
		cli zrpc.Client
	}
)

func NewMarket(cli zrpc.Client) Market {
	return &defaultMarket{
		cli: cli,
	}
}

func (m *defaultMarket) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultMarket) GetPairInfoByToken(ctx context.Context, in *GetPairInfoByTokenRequest, opts ...grpc.CallOption) (*GetPairInfoByTokenResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetPairInfoByToken(ctx, in, opts...)
}

func (m *defaultMarket) GetNativeTokenPrice(ctx context.Context, in *GetNativeTokenPriceRequest, opts ...grpc.CallOption) (*GetNativeTokenPriceResponse, error) {
	client := market.NewMarketClient(m.cli.Conn())
	return client.GetNativeTokenPrice(ctx, in, opts...)
}
