// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: market.proto

package server

import (
	"context"

	"greet/market/internal/logic"
	"greet/market/internal/svc"
	"greet/market/market"
)

type MarketServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServer
}

func NewMarketServer(svcCtx *svc.ServiceContext) *MarketServer {
	return &MarketServer{
		svcCtx: svcCtx,
	}
}

func (s *MarketServer) Ping(ctx context.Context, in *market.Request) (*market.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *MarketServer) GetPairInfoByToken(ctx context.Context, in *market.GetPairInfoByTokenRequest) (*market.GetPairInfoByTokenResponse, error) {
	l := logic.NewGetPairInfoByTokenLogic(ctx, s.svcCtx)
	return l.GetPairInfoByToken(in)
}

func (s *MarketServer) GetNativeTokenPrice(ctx context.Context, in *market.GetNativeTokenPriceRequest) (*market.GetNativeTokenPriceResponse, error) {
	l := logic.NewGetNativeTokenPriceLogic(ctx, s.svcCtx)
	return l.GetNativeTokenPrice(in)
}
