// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trade.proto

package server

import (
	"context"

	"greet/trade/internal/logic"
	"greet/trade/internal/svc"
	"greet/trade/trade"
)

type TradeServer struct {
	svcCtx *svc.ServiceContext
	trade.UnimplementedTradeServer
}

func NewTradeServer(svcCtx *svc.ServiceContext) *TradeServer {
	return &TradeServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServer) Ping(ctx context.Context, in *trade.Request) (*trade.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
